### ISSUE TITLE
Out of memory?

### ISSUE THREAD

**Issue by nicholascdove** [DaliangNing/iCAMP1#21] opened 2022-02-14 21:22 UTC
Thanks for the great package! I've run this on a dataset before without issue. However, I am having difficulty running the icamp.big() command with my current dataset. The output says:

> ----------Now binning-----------------Fri Feb 11 13:02:56 2022
> Now computing path. begin at Fri Feb 11 13:03:04 2022. Please wait...
> Now computing path. begin at Fri Feb 11 13:06:18 2022. Please wait...
> Now computing dist to root. begin at Fri Feb 11 13:06:32 2022. Please wait...
>
> ----------Now binning com and sp without omitting small bins-----------------Fri Feb 11 13:08:22 2022
> ----bMPD bin i=1 in 13 ---- Fri Feb 11 13:08:23 2022
> Now calculating observed betaMPD. Begin at Fri Feb 11 13:08:48 2022. Please wait...
> Now randomizing by parallel computing. Begin at Fri Feb 11 13:11:32 2022. Please wait...
> Error in serialize(data, node$con) : ignoring SIGPIPE signal
> Calls: <Anonymous> ... postNode -> sendData -> sendData.SOCKnode -> serialize
> Execution halted

It appears the task has run out of memory. Does this seem to be the case? I am running this on 32 cores with 350 G of memory. The dataset is large, but not exceptionally so (87 samples and 39675 ASVs). Is it just a matter of giving the job more memory, or is there perhaps a different underlying issue? 

A portion of my code is presented below. Thanks!

> nworker = 32
> memory.G = 350
> rand.time = 1000
> bin.size.limit = 24 
> sig.index="Confidence" 
>
> icres=iCAMP::icamp.big(comm=comm, pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label, 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pd.wd = pd.big$pd.wd, rand = rand.time, tree=tree,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prefix = prefix, ds = 0.2, pd.cut = NA, sp.check = TRUE,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phylo.rand.scale = "within.bin", taxa.rand.scale = "across.all",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phylo.metric = "bMPD", sig.index=sig.index, bin.size.limit = bin.size.limit,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nworker = nworker, memory.G = memory.G, rtree.save = FALSE, detail.save = TRUE,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qp.save = FALSE, detail.null = FALSE, ignore.zero = TRUE, output.wd = save.wd,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;correct.special = TRUE, unit.sum = rowSums(comm), special.method = "depend",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ses.cut = 1.96, rc.cut = 0.95, conf.cut=0.975, omit.option = "no",meta.ab = NULL)

**Comment by DaliangNing** [comment] 2022-02-16 20:03
I have no idea about the error. iCAMP uses the bigmemory package to call the large phylogenetic distance matrix from the hard drive rather than memory. Your memory should be more than enough. I guess it may work if you reduce the nworker to 24, to avoid using up all CPU resources.

**Comment by nicholascdove** [comment] 2022-02-16 21:05
Thanks for the tip! I will try this and get back to you.

**Comment by DaliangNing** [comment] 2022-02-21 21:33
Has your problem been solved? If no more questions, I will close this issue soon.

**Comment by nicholascdove** [comment] 2022-02-23 13:53
Unfortunately, I received the same error.

**Comment by DaliangNing** [comment] 2022-02-23 19:25
Then i have no idea. If you do not mind, you can send me (ningdaliang@ou.edu) your input files (like ASV table, tree, etc.) and R code (with your choice of key parameters). I can try it on our server.

**Comment by nicholascdove** [comment] 2022-02-28 19:06
Thanks Daliang. I just sent it over.

**Comment by DaliangNing** [comment] 2022-04-21 20:18
I am closing this issue now. The problem is caused by the phylogenetic tree. The node number in the tree is abnormally low compared to the tip number. Reconstructing the phylogenetic tree should solve the problem.

**Closed by DaliangNing** 2022-04-21 20:18 UTC

**Comment by hahamark-learn** [comment] 2023-08-02 01:57
hello, I get the same error. I check the node number in the tree, the number isn't abnormally low compared to the tip number.

**Comment by hahamark-learn** [comment] 2023-08-02 02:01
----bMPD bin i=15 in 435 ---- Tue Aug  1 21:42:18 2023
Now calculating observed betaMPD. Begin at Tue Aug  1 21:42:18 2023. Please wait...
Now randomizing by parallel computing. Begin at Tue Aug  1 21:43:31 2023. Please wait...
Now fixing special cases. Begin at Tue Aug  1 21:44:54 2023. Please wait...
All match very well.
Now calculating observed MPD. Begin at Tue Aug  1 21:44:55 2023. Please wait...
Error in makePSOCKcluster(names = spec, ...) :
  Cluster setup failed. 15 of 15 workers failed to connect.
Error in makePSOCKcluster(names = spec, ...) :
  Cluster setup failed. 14 of 15 workers failed to connect.
Now randomizing by parallel computing. Begin at Tue Aug  1 21:47:54 2023. Please wait...
Error in serialize(data, node$con) : ignoring SIGPIPE signal
